services:
  avito-shop-service:
    build: .
    container_name: avito-shop-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - migrations
    networks:
      - internal
    env_file:
      - .env

  migrations:
    image: ghcr.io/kukymbr/goose-docker:3.24.1
    restart: no
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=user=service-user password=SomeHardPassw0rd dbname=avito-shop host=postgres port=5432 sslmode=disable
      - GOOSE_VERBOSE=true
      - GOOSE_COMMAND=up
    volumes:
      - ./migrations:/migrations
    networks:
      - internal

  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d avito-shop" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal

networks:
  internal:
