package consts

const (
	// APIFolder ...
	APIFolder = "api"
	// SwaggerPath ...
	SwaggerPath = "/swagger"
	// AuthPath ...
	AuthPath = "/api/auth"
	// AuthTokenCookie ...
	AuthTokenCookie = "auth_token"
)
